---
- name: Install k3s Master
  shell: "curl -sfL https://get.k3s.io | sh -s -- --disable=servicelb"
  args:
    creates: /usr/local/bin/k3s

- name: Get k3s Node Token
  command: cat /var/lib/rancher/k3s/server/node-token
  register: k3s_token
  changed_when: false

- name: Save k3s Node Token for Workers to Use
  set_fact:
    k3s_node_token: "{{ k3s_token.stdout }}"

- name: Ensure ExecStart is configured with external IP
  lineinfile:
    path: /etc/systemd/system/k3s.service
    backrefs: yes
    regexp: '^(ExecStart=.*/k3s \\\n\s*server)'
    line: '\1 --node-external-ip 3.64.217.54 \\'
    state: present

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: Restart k3s service
  systemd:
    name: k3s
    state: restarted
