---
- name: Install k3s on Master Node
  hosts: _k3s_master
  become: yes
  roles:
    - k3s_master

- name: Install k3s on Worker Nodes
  hosts: _k3s_worker
  become: yes
  roles:
    - k3s_worker
# - name: Install k3s on Worker on prem Nodes
#   hosts: _k3s_worker_on_prem
#   become: yes
#   roles:
#     - k3s_worker_on_prem
