name: Run Python Script in Docker

on:
  push:
    branches:
      - master
    paths:
      - "labs/**"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./labs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t my-python-app .

      - name: Run Script in Docker
        run: docker run my-python-app python /path/to/lab5.py
