name: Run Python Script

on:
  push:
    paths:
      - "labs/**"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: ./labs

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create and activate virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Script
        run: |
          source venv/bin/activate
          venn/bin/python lab5.py
